### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Merlignux** [jfcolom/rosary#2]
I would like to translate the app to Portuguese.

Is there a place such as transifex or weblate where i can do it?

**Comment by jfcolom** [comment]
Hello @Merlignux,

Sorry to come up so late with this issue, and thank you for the interest shown.

This is a very simple app. In fact this is more a web page than an app. You can find the single page [here](https://github.com/jfcolom/rosary/blob/master/app/src/main/assets/www/index.html) and the background image [here](https://github.com/jfcolom/rosary/blob/master/app/src/main/assets/www/img/bkg.jpg) (of course, feel free to use another one).

It is not difficult to get the texts by reading index.html (from line 62 to 120), then you can translate them using any service you like. You can also upload your ``index.html``  and your ``bkg.jpg`` to some hosting service and run it as a web page instead of as an app.

Of course, it will be more useful if the app lets the user to choose a language and propose a list of supported ones. Maybe the language selection could come from the user Android configuration. I hope to find some time in the future to implement features like that.
